version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: dataDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
